FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./src/ .

EXPOSE 5000

CMD  ["flask", "--app", "app", "run", "--host=0.0.0.0"]